#!/usr/bin/python3
"""





#####################################################################
    

                        DO NOT EDIT THIS FILE


#####################################################################






"""
import unittest
from main import capitalize
class Tests(unittest.TestCase):
    def test(self):
        self.assertEqual(capitalize("hello world"),"Hello world")
        self.assertEqual(capitalize("python"),"Python")

        
if __name__=='__main__':
    unittest.main()
